/*
 * DO NOT EDIT MANUALLY
 * Generated via 'make update-ff-translations'
 */
export const titles = {
"Aslaɣ n uvidyu":true,
"Beeld-in-Beeld":true,
"Bideoa beste leiho batean":true,
"Bilde-i-bilde":true,
"Bild-i-bild":true,
"Bild-im-Bild":true,
"Bildo en bildo":true,
"Billede-i-billede":true,
"Dealbh am broinn deilbh":true,
"Gambar-dalam-Gambar":true,
"Görüntü içinde görüntü":true,
"Hình trong hình":true,
"Imachen sobre imachen":true,
"Imagine-in-imagine":true,
"Imagine în imagine":true,
"Imatge sobre imatge":true,
"Imaxe en imaxe":true,
"Imaxe sobre imaxe":true,
"Immàgine-subra-immàgine":true,
"Incrustation vidéo":true,
"Kép a képben":true,
"Kuva kuvassa":true,
"Llun mewn Llun":true,
"Maletg-en-maletg":true,
"Mmàggini-nnâ-Mmàggini":true,
"Mynd-í-mynd":true,
"Obraz v obraze":true,
"Obraz w obrazie":true,
"Ôbroz w ôbrazie":true,
"Pictiúr i bPictiúr":true,
"Picture-in-picture":true,
"Picture-in-Picture":true,
"Pictur-in-Pictur":true,
"Pilt-pildis":true,
"Sa ni'io' Riña sa ni'io'":true,
"Şəkildə-Şəkil":true,
"Skeudenn-ouzh-skeudenn":true,
"Slika u slici":true,
"Slika-u-slici":true,
"Slika v sliki":true,
"화면 속 화면":true,
"Vaizdas-vaizde":true,
"Vatzib'al":true,
"Vídeo em janela flutuante":true,
"Vidèo incrustada":true,
"Wobraz-we-wobrazu":true,
"Εικόνα εντός εικόνας":true,
"Выява ў выяве":true,
"Зображення в зображенні":true,
"Картина в картината":true,
"Картинка в картинке":true,
"Расм-дар-расм":true,
"Слика у слици":true,
"Суреттегі сурет":true,
"ეკრანი-ეკრანში":true,
"Նկար նկարում":true,
"Նկար֊նկարում":true,
"תמונה בתוך תמונה":true,
"تصویر در تصویر":true,
"تصویر میں تصویر":true,
"تصویر وِچ تصویر":true,
"ڤديو معترِض":true,
"وێنە-لەناو-وێنە":true,
"पिक्चर-इन-पिक्चर":true,
"सावगारि-गेजेरौ-सावगारि":true,
"ছবির মধ্যে ছবি":true,
"ছবিৰ-ওপৰত-ছবি":true,
"ਤਸਵੀਰ-ਚ-ਤਸਵੀਰ":true,
"රූපයෙන් රූපයට":true,
"ภาพที่เล่นควบคู่":true,
"ᱪᱤᱛᱟᱹᱨᱼᱵᱷᱤᱛᱨᱤᱼᱪᱤᱛᱟᱹᱨ":true,
"ピクチャーインピクチャー":true,
"子母畫面":true,
"画中画":true
}

